version: "3"

services:
  tor-privoxy:
    restart: always
    image: rmamba/tor-privoxy-ip-check:latest
    ports:
      - "9050:9050" # Tor proxy
      - "9051:9051" # Tor control port
      - "8118:8118" # Privoxy
    healthcheck:
      test: /tmp/testIP https://api.ipify.org?format=json || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
